tmp_dir:
  "/scratch/fanslerm"

metadataFile:
  "metadata/E-MTAB-7391.sdrf.txt"

chromSizes:
  "/data/mayrc/db/mm10/mm10.chrom.sizes"

utromeGTF:
  "/data/mayrc/data/mca/gff/utrome.e30.t5.gc25.pas3.f0.9999.w500.gtf"

utromeKDX:
  "/data/mayrc/data/mca/kdx/utrome.e30.t5.gc25.pas3.f0.9999.w500.kdx"

utromeMerge:
  "/data/mayrc/data/mca/gff/utrome.e30.t5.gc25.pas3.f0.9999.w500.m200.tsv"

atlasUTRAnnots:
  "/data/mayrc/data/atlas-mm/utrs/utrome_txs_annotation.Rds"

atlasGeneAnnots:
  "/data/mayrc/data/atlas-mm/data/utrs/utrome_genes_annotation.Rds"
  
hisat2:
  "/data/mayrc/software/hisat2-2.1.0/hisat2"

hisat2Index:
  "/data/mayrc/achursov/sequencing/genomes/mouse/mm10/indexes/hisat2/mm10_hisat2"

samtools:
  "/home/fanslerm/software/miniconda3/bin/samtools"
